"""Add classrooms

Revision ID: 0194bf108284
Revises: 3e5120099b75
Create Date: 2025-02-06 21:38:36.865887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0194bf108284'
down_revision: Union[str, None] = '3e5120099b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_id'), 'classroom', ['id'], unique=False)
    op.create_table('classroom_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_membership_id'), 'classroom_membership', ['id'], unique=False)
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.execute("""UPDATE "user" SET role = 1""")
    op.alter_column('user', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_classroom_membership_id'), table_name='classroom_membership')
    op.drop_table('classroom_membership')
    op.drop_index(op.f('ix_classroom_id'), table_name='classroom')
    op.drop_table('classroom')
    # ### end Alembic commands ###
