"""nonnull_try_count

Revision ID: 0b5c83810202
Revises: 81c206ddaf47
Create Date: 2025-05-24 13:16:21.900913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5c83810202'
down_revision: Union[str, None] = '81c206ddaf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('level_session', 'try_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('level_session', 'try_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
