"""New schema

Revision ID: 3e5120099b75
Revises: 4a5f3f53754c
Create Date: 2025-01-11 11:08:58.868403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e5120099b75'
down_revision: Union[str, None] = '4a5f3f53754c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('finish_secret', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('level_key', sa.String(), nullable=False),
    sa.Column('level_metadata', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_session_id'), 'level_session', ['id'], unique=False)
    op.drop_index('ix_levelsession_id', table_name='levelsession')
    op.drop_table('levelsession')
    op.drop_index('ix_level_id', table_name='level')
    op.drop_table('level')
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_constraint('user_nickname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_nickname_key', 'user', ['nickname'])
    op.drop_column('user', 'last_login')
    op.create_table('level',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('level_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('category', postgresql.ENUM('Elements', 'Network', name='categoryenum'), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_in_category', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='level_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_level_id', 'level', ['id'], unique=False)
    op.create_table('levelsession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('level_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], name='levelsession_level_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='levelsession_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='levelsession_pkey')
    )
    op.create_index('ix_levelsession_id', 'levelsession', ['id'], unique=False)
    op.drop_index(op.f('ix_level_session_id'), table_name='level_session')
    op.drop_table('level_session')
    # ### end Alembic commands ###
