"""add_trycount

Revision ID: 81c206ddaf47
Revises: ddea3fde59cc
Create Date: 2025-05-24 13:14:34.514376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c206ddaf47'
down_revision: Union[str, None] = 'ddea3fde59cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level_session', sa.Column('try_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level_session', 'try_count')
    # ### end Alembic commands ###
