"""removeclasrooms

Revision ID: ddea3fde59cc
Revises: 0194bf108284
Create Date: 2025-05-24 13:12:47.401817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddea3fde59cc'
down_revision: Union[str, None] = '0194bf108284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_membership_id', table_name='classroom_membership')
    op.drop_table('classroom_membership')
    op.drop_index('ix_classroom_id', table_name='classroom')
    op.drop_table('classroom')
    op.drop_column('user', 'email')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('classroom',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classroom_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='classroom_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='classroom_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_classroom_id', 'classroom', ['id'], unique=False)
    op.create_table('classroom_membership',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], name='classroom_membership_classroom_id_fkey'),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], name='classroom_membership_member_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='classroom_membership_pkey')
    )
    op.create_index('ix_classroom_membership_id', 'classroom_membership', ['id'], unique=False)
    # ### end Alembic commands ###
